---
PURELYMAIL_API_TOKEN: ${PURELYMAIL_API_TOKEN}
PURELYMAIL_DOMAIN: ${PURELYMAIL_DOMAIN}
PURELYMAIL_USER_PASSWORD: ${PURELYMAIL_USER_PASSWORD}
PURELYMAIL_API_TLS_VERIFY: ${PURELYMAIL_API_TLS_VERIFY:-true}
