---
PURELYMAIL_API_TOKEN: ${PURELYMAIL_API_TOKEN}
PURELYMAIL_TEST_DOMAIN_PRIMARY: ${PURELYMAIL_TEST_DOMAIN_PRIMARY}
PURELYMAIL_TEST_DOMAIN_SECONDARY: ${PURELYMAIL_TEST_DOMAIN_SECONDARY}
PURELYMAIL_TEST_DOMAIN_TERTIARY: ${PURELYMAIL_TEST_DOMAIN_TERTIARY}
PURELYMAIL_USER_PASSWORD: ${PURELYMAIL_USER_PASSWORD}
PURELYMAIL_API_TLS_VERIFY: ${PURELYMAIL_API_TLS_VERIFY:-true}
